#!/bin/bash
for rpi in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18;do
	ping -c 1 rpi$rpi >/dev/null
	if [ $? -eq 0 ]
	then
	echo " rpi$rpi :  alive "
	else
	echo " rpi$rpi :  dead "
	fi
done

